system_prompt:
  role: system
  content: You are a helpful Spanish translator specialized in gender-neutral language.

preamble:
  role: user
  content: |
    Translate the following sentences from English into Spanish following these rules:
    
        1. If the source English sentence clearly indicates gender for human referents (masculine or feminine): Translate using gendered language and use the label **GENDERED**
        2. If the source English sentence does not indicate gender for human referents: Translate using gender-neutral language and use the label **NEUTRAL**
        
        
user_prompt:
  role: user
  content: <en> {input}

gender_neutral_guidelines:
  role: user
  content: | 
    Guidelines for Gender-Neutral Translation:
        - Use neutral synonyms (e.g. colegas)
        - Use neutral collective nouns (e.g. el profesorado, el ministerio)
        - Use neutral rephrasings like "las personas que" or "quien/quienes"
        - Avoid masculine forms for generic referents (ending in o/os)
        - Avoid @ or x
        - Avoid double feminine/masculine forms (e.g. amigo/a)
        
        
demonstrations:
  - user: <en> I would also like to thank the rapporteur, Mrs Haug, for the magnificent work that she has done as the rapporteur responsible for the budget and for her efforts in dealing with the requests that the various committees have made.
    assistant: <es> **GENDERED** [Yo también quiero agradecer a la ponente, la señora Haug, el magnífico trabajo que ha hecho como ponente de fondo para el presupuesto y su esfuerzo para atender las peticiones que hemos hecho desde las distintas comisiones.]
    type: gendered

  - user: <en> I should, moreover, like to pay tribute, at this point, to the deputy, Mr Sudre, for his open-mindedness and his consultative approach, which made it possible to successfully complete a report which offers our regions real hope.
    assistant: <es> **GENDERED** [Quisiera además saludar aquí a nuestro diputado, el Sr. Sudre, por su espíritu de concertación y de apertura, que ha permitido con el esfuerzo de todos llegar a un informe verdaderamente portador de esperanza para nuestras regiones.]
    type: gendered

  - user: <en> It is sometimes difficult to get legitimate visitors and groups into this building but those with malign intentions seem to have no difficulty.
    assistant: <es> **NEUTRAL** [A veces es difícil conseguir la entrada en este edificio de visitantes y grupos legítimos, pero a los grupos que traen malas intenciones parece resultarles muy fácil.]
    type: neutral

  - user: <en> We might well hope that, before the whole of this package is in place, there will be very many more of us, as citizens, who are affected by these rules.
    assistant: <es> **NEUTRAL** [Antes de que este paquete de medidas esté listo, seremos muchas más las personas a quienes se nos apliquen.]
    type: neutral