system_prompt:
  role: system
  content: You are a helpful German translator specialized in gender-neutral language.

preamble:
  role: user
  content: |
    Translate the following sentences from English into German following these rules:
    
        1. If the source English sentence clearly indicates gender for human referents (masculine or feminine): Translate using gendered language and use the label **GENDERED**
        2. If the source English sentence does not indicate gender for human referents: Translate using gender-neutral language and use the label **NEUTRAL**
        
        
user_prompt:
  role: user
  content: <en> {input}

gender_neutral_guidelines:
  role: user
  content: | 
    Guidelines for Gender-Neutral Translation:
        - Use neutral synonyms (e.g. Studierende instead of Studenten)
        - Use neutral collective nouns (e.g. die Lehrkräfte, das Ministerium)
        - Use neutral rephrasings like "die Personen, die"
        - Avoid masculine forms for generic referents (e.g. der/die Präsident/en)
        - Avoid  Binnen-I, Gendersternchen (*), o Unterstriche (_)
        - Avoid double feminine/masculine forms (e.g. Kollege/Kollegin)
        
        
demonstrations:
  - user: <en> I would also like to thank the rapporteur, Mrs Haug, for the magnificent work that she has done as the rapporteur responsible for the budget and for her efforts in dealing with the requests that the various committees have made.
    assistant: <de> **GENDERED** [Frau Präsidentin! Auch ich möchte der Berichterstatterin, Frau Haug, für ihre hervorragende Arbeit als Hauptberichterstatterin für den Haushalt und für ihr Bemühen, den Wünschen der verschiedenen Ausschüsse Rechnung zu tragen, meinen Dank aussprechen.]
    type: gendered

  - user: <en> I should, moreover, like to pay tribute, at this point, to the deputy, Mr Sudre, for his open-mindedness and his consultative approach, which made it possible to successfully complete a report which offers our regions real hope.
    assistant: <de> **GENDERED** [Ich möchte hier auch unserem Stellvertreter, Herrn Sudre, meine Anerkennung für seine Offenheit und seine Bereitschaft, sich mit allen abzustimmen, aussprechen, die ermöglicht haben, einen Bericht vorzulegen, der unseren Regionen wirklich Hoffnung bringt.]
    type: gendered

  - user: <en> It is sometimes difficult to get legitimate visitors and groups into this building but those with malign intentions seem to have no difficulty.
    assistant: <de> **NEUTRAL** [Es ist gelegentlich schwierig, anständige Gäste und Gruppen in dieses Gebäude zu bekommen, aber Personen mit üblen Absichten scheinen damit keine Probleme zu haben.]
    type: neutral

  - user: <en> We might well hope that, before the whole of this package is in place, there will be very many more of us, as citizens, who are affected by these rules.
    assistant: <de> **NEUTRAL** [Wir können aber wohl darauf hoffen, dass es vor der Annahme des gesamten Pakets noch erheblich mehr Menschen sein werden, die von diesen Regelungen betroffen sind.]
    type: neutral