system_prompt:
  role: system
  content: You are a helpful Italian translator specialized in gender-neutral language.

preamble:
  role: user
  content: |
    Translate the following sentences from English into Italian following these rules:
    
        1. If the source English sentence clearly indicates gender for human referents (masculine or feminine): Translate using gendered language and use the label **GENDERED**
        2. If the source English sentence does not indicate gender for human referents: Translate using gender-neutral language and use the label **NEUTRAL**
        
        
user_prompt:
  role: user
  content: <en> {input}

gender_neutral_guidelines:
  role: user
  content: "Guidelines for Gender-Neutral Translation:
        - Use neutral synonyms (e.g. collega)
        - Use neutral collective nouns (e.g. il corpo docente, il ministero)
        - Use neutral rephrasings like \"le persone che\" or \"chi/coloro\"
        - Avoid masculine forms for generic referents (ending in o/i)
        - Avoid \u0259 or *
        - Avoid double feminine/masculine forms (e.g. amico/a)\n"
        
demonstrations:
  - user: <en> I would also like to thank the rapporteur, Mrs Haug, for the magnificent work that she has done as the rapporteur responsible for the budget and for her efforts in dealing with the requests that the various committees have made.
    assistant: <it> **GENDERED** [Ringrazio a mia volta la relatrice, onorevole Haug, per l'eccellente lavoro svolto intorno al bilancio in qualità di relatrice sul merito, e la ringrazio per avere tentato di tener conto delle istanze delle varie commissioni parlamentari.]
    type: gendered

  - user: <en> I should, moreover, like to pay tribute, at this point, to the deputy, Mr Sudre, for his open-mindedness and his consultative approach, which made it possible to successfully complete a report which offers our regions real hope.
    assistant: <it> **GENDERED** [Vorrei peraltro ringraziare il deputato, l'onorevole Sudre, per il suo spirito di concertazione e di apertura che ha consentito di realizzare una relazione che è veramente latrice di speranza per le nostre regioni.]
    type: gendered

  - user: <en> It is sometimes difficult to get legitimate visitors and groups into this building but those with malign intentions seem to have no difficulty.
    assistant: <it> **NEUTRAL** [Talvolta è difficile avere in questa sede le persone invitate e i gruppi desiderati, mentre sembra che gli individui che hanno cattive intenzioni non abbiano alcuna difficoltà ad entrare.]
    type: neutral

  - user: <en> We might well hope that, before the whole of this package is in place, there will be very many more of us, as citizens, who are affected by these rules.
    assistant: <it> **NEUTRAL** [Speriamo che, prima dell'entrata in vigore del pacchetto nella cittadinanza il numero di persone interessate da queste norme sia ancora più alto.]
    type: neutral